### ISSUE TITLE
Refresh on first load to enable functionality.

### ISSUE THREAD

**Issue by jon49** [richardanaya/wasm-service#2]
This is really cool, I'm not super familiar with Rust (I've played with it a little in the past). But I've been developing my personal apps that I make for myself for a while, I use my own `HTMF` lib instead of `HTMX` as I don't need the full power of `HTMX` and `HTMF` is built out of the box to use progressive enhancement. So, it wouldn't be that difficult to make this code work on the back end and front end and be progressively enhanced.

But here's how to implement an auto updater for service workers (the first time I load on a new machine I automatically refresh the page):

<https://github.com/jon49/Soccer/blob/172e6e6043583c862d96d6e5ff9613cb7021d155/Soccer/FrontEnd/src/web/js/main.v9.ts#L7>
<https://github.com/jon49/Soccer/blob/172e6e6043583c862d96d6e5ff9613cb7021d155/Soccer/FrontEnd/src/web/sw.ts#L33>

<https://github.com/jon49/htmf>
<https://github.com/jon49/Soccer>

I definitely like the idea of running with Rust as node.js is painfully slow on the back end and I would prefer C# but I don't want to download 1 MB just for a tiny website (I think all the JS I have for my soccer website is around 50k).

**Comment by infogulch** [comment]
Nice idea, you inspired me to take a crack at refreshing behavior in PR #3.

I think it would be neat to aim for a progressive enhancement design where you take the same wasm app server code from your traditional web server on a vm and place it closer to the user in a service worker or web worker. I think a few different modes would be useful:

0. nojs mode, all interactions reload the whole page from the remote server
1. light mode, just run htmx js locally which makes queries to the remote server to load targeted sections of the page
2. app mode, like light mode but where the server runs locally in a service worker instead of a remote vm

(If we bundle in [sqlite3](https://sqlite.org/wasm/doc/tip/about.md) we'd really be cooking, but we're not quite there yet. 😄 )

**Comment by richardanaya** [comment]
@infogulch thanks for the PR, happy you are inspired.

**Comment by infogulch** [comment]
I think this issue can be closed since it was solved in #3.
